### PR TITLE
RHSTOR-5879: Annotate storageclasses for Reclaimspace by ocs-client-o…

### PR DESCRIPTION
**Pull request by Mrudraia**
This PR adds ReclaimSpace Annotations on RBD StorageClasses, for Auto ReclaimSpace operations.
The default schedule is set to weekly.

### CODE REVIEW

**Comment by rchikatw** [comment]
Add a description to the PR & fix the commitlint issue

**Comment by leelavg** [comment]
@Mrudraia pls change the PR description, there is no explicit need to mention `ocs-client-operator`. Please provide testing results to approve this PR.

Expand PR description on what the added option does as well. I see you are not changing anything but adding annotation and not sure what this supposed to do.

**Comment by Mrudraia** [comment]
> @Mrudraia pls change the PR description, there is no explicit need to mention `ocs-client-operator`. Please provide testing results to approve this PR.
> 
> Expand PR description on what the added option does as well. I see you are not changing anything but adding annotation and not sure what this supposed to do.

PR description modified

**Comment by leelavg** [comment]
> Please provide testing results to approve this PR.
- Did you test the feature?

**Comment by Mrudraia** [comment]
> > Please provide testing results to approve this PR.
> 
> * Did you test the feature?

Tested PR with custom-build of ocs-client-operator, The annotation is added the rbd storageclass 

`oc get storageclasses/ocs-storagecluster-ceph-rbd -o yaml 


apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    description: Provides RWO Filesystem volumes, and RWO and RWX Block volumes
    ocs.openshift.io/storageclaim: ocs-storagecluster-ceph-rbd
    reclaimspace.csiaddons.openshift.io/schedule: '@weekly'
  creationTimestamp: "2024-07-10T11:12:29Z"
 `

**Review by iPraveenParihar — APPROVED** [review]

**Comment by Madhu-1** [comment]
@iPraveenParihar @Mrudraia have we tested the complete flow to make sure everything works?

**Comment by Madhu-1** [comment]
> @iPraveenParihar @Mrudraia have we tested the complete flow to make sure everything works?

sorry missed earlier update related to testing

**Review by Madhu-1 — APPROVED** [review]

**Pull request merged**
