### PR TITLE
api: adding clusterresourcequotaspec hash to status

### PR DESCRIPTION
**Pull request by rchikatw**
adding clusterresourcequotaspec hash to status to status section of storage client

### CODE REVIEW

**Comment by rchikatw** [comment]
@leelavg please review...

**Comment by leelavg** [comment]
/hold

the intention is to replace/enhance the existing comms w/ a hash but not only for quota.

**Comment by leelavg** [comment]
close if #200 supersedes this PR.

**Comment by rchikatw** [comment]
Closing this PR as this has been tracked with another approach and tracked in different PR. https://github.com/red-hat-storage/ocs-client-operator/pull/200

**Pull request closed without merging**
