### PR TITLE
api: update console API from v1alpha1 to v1

### PR DESCRIPTION
**Pull request by leelavg**
console plugin API is promoted to v1 around Apr 2022 and deprecated in OCP 4.17 and this PR uses v1 API to be inline w/ odf-console

ref: openshift/api/pull/[1186]

### CODE REVIEW

**Comment by leelavg** [comment]
client-op now reconciles on 4.17 w/o any issues
```
2024-07-15T11:41:16Z    INFO    prometheus rules deployed       {"controller": "configmap", "controllerGroup": "", "controllerKind": "ConfigMap", "ConfigMap": {"name":"ocs-client-operator-config","namespace":"openshift-storage"}, "namespace": "openshift-storage", "name": "ocs-client-operator-config", "reconcileID": "662f45d9-03da-4b81-a7d8-f9b31957d92c", "OperatorConfigMap": {"name":"ocs-client-operator-config","namespace":"openshift-storage"}, "prometheusRule": {"name":"prometheus-pvc-rules","namespace":"openshift-storage"}}
```

awaiting new client-console to verify against it.

**Review by Madhu-1 — COMMENTED** [review]
LGTM, let me know when to merge this one

**Review by Madhu-1 — APPROVED** [review]

**Comment by SanjalKatiyar** [comment]
> * could you pls pass on BZ raised for odf-op for back-porting similar fix to 4.16?

I don't think we have a BZ for backport (cc @iamniting ??)

> * I think backport is required as for a brief period of time 4.16 operator could be run on 4.17 platform and since there'll be no webhook in ocp 4.17 to convert console api from v1a1 to v1 controllers could be stalled. Open to be corrected.

I think u r right, it can break !

**Comment by iamniting** [comment]
> > * could you pls pass on BZ raised for odf-op for back-porting similar fix to 4.16?
> 
> I don't think we have a BZ for backport (cc @iamniting ??)

I don't have BZ either, Do we really need a backport, It should be supported in 4.16. Isn't it?

> 
> > * I think backport is required as for a brief period of time 4.16 operator could be run on 4.17 platform and since there'll be no webhook in ocp 4.17 to convert console api from v1a1 to v1 controllers could be stalled. Open to be corrected.
> 
> I think u r right, it can break !

**Comment by leelavg** [comment]
> It should be supported in 4.16. Isn't it?
- 4.16 ODF on 4.17 OCP, during upgrades 4.16 ODF controllers could stall afaiu.

**Comment by iamniting** [comment]
Here it is https://bugzilla.redhat.com/show_bug.cgi?id=2297946

**Comment by leelavg** [comment]
I see PR of go version in odf-op is linked to the BZ and I don't think we were using 1.22 in 4.16 branch, just an heads up/pls double check.

**Comment by iamniting** [comment]
> I see PR of go version in odf-op is linked to the BZ and I don't think we were using 1.22 in 4.16 branch, just an heads up/pls double check.

We will have to get only a second commit from both the PR.

**Pull request merged**
