### PR TITLE
ci: add leelavg to OWNERS files

### PR DESCRIPTION
**Pull request by leelavg**

### CODE REVIEW

**Comment by Madhu-1** [comment]
@leelavg looks like golanci-lint is failing due to some updates in job, can you please take care of it in another PR as its not related to this?

**Comment by Madhu-1** [comment]
okay looks like those jobs need to be successful, can you please add new commit to this PR to fix it :)

**Comment by leelavg** [comment]
depends on #76 

thanks for the reminder Madhu.

**Pull request merged**
