### PR TITLE
Bug 2247737: add APIs to scheme, role and role binding to bundle

### PR DESCRIPTION
**Pull request by leelavg**
- Add missing ClusterVersion and ClusterServiceVersion APIs to status reporter Scheme
- Add missing Role and RoleBinding to Kustomize and generate CSV Bundle

### CODE REVIEW

**Comment by nb-ohad** [comment]
LGTM

**Comment by leelavg** [comment]
Without fix:
```
$ k logs storageclient-abf16dbc3c286256-status-reporter-28316498-qj82x
W1103 05:39:24.428516       1 main.go:90] Failed to list csv resources: no kind is registered for the type v1alpha1.ClusterServiceVersionList in scheme "/remote-source/app/service/status-report/main.go:45"
W1103 05:39:24.428604       1 main.go:100] Unable to find csv with prefix "ocs-client-operator"
W1103 05:39:24.428613       1 main.go:107] Failed to get clusterVersion: no kind is registered for the type v1.ClusterVersion in scheme "/remote-source/app/service/status-report/main.go:45"
W1103 05:39:24.428620       1 main.go:117] Unable to find ocp version with completed update
F1103 05:39:24.438907       1 main.go:134] Failed to report status of storageClient 1cbb0e37-301b-427f-9b96-2161e4d48236: rpc error: code = InvalidArgument desc = Malformed ClientPlatformVersion: Version string empty
```

With fix:
``` yaml
$ cat storageclient-29011.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: storageclient-29011-status-reporter
  namespace: openshift-storage-client
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /status-reporter
            env:
            - name: STORAGE_CLIENT_NAMESPACE
              value: openshift-storage-client
            - name: STORAGE_CLIENT_NAME
              value: storageclient
            - name: OPERATOR_NAMESPACE
              value: openshift-storage-client
            image: quay.io/rhn_support_lgangava/code:29011
            imagePullPolicy: IfNotPresent
            name: heartbeat
          serviceAccount: ocs-client-operator-status-reporter
          serviceAccountName: ocs-client-operator-status-reporter
          terminationGracePeriodSeconds: 30
          restartPolicy: OnFailure
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ocs-client-operator-status-reporter
  namespace: openshift-storage-client
rules:
- apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
  verbs:
  - get
  - list
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ocs-client-operator-status-reporter
  namespace: openshift-storage-client
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ocs-client-operator-status-reporter
subjects:
  - kind: ServiceAccount
    name: ocs-client-operator-status-reporter
    namespace: openshift-storage-client
---
```

```
$ k logs storageclient-29011-status-reporter-28316499-87v9d
[....EMPTY...]
```

``` yaml
$ k get storageconsumer storageconsumer-f4aec37d-d6de-4ea2-9d4c-4210170a4f92 -oyaml | yq 'del(.metadata.annotations)'
apiVersion: ocs.openshift.io/v1alpha1
kind: StorageConsumer
metadata:
  creationTimestamp: "2023-10-29T03:49:30Z"
  generation: 2
  name: storageconsumer-f4aec37d-d6de-4ea2-9d4c-4210170a4f92
  namespace: openshift-storage
  resourceVersion: "21003071"
  uid: 1cbb0e37-301b-427f-9b96-2161e4d48236
spec:
  enable: true
status:
  cephResources:
    - kind: CephClient
      name: 126102a1ddafcaa8045be5cfb98746c0
      status: Ready
  client:
    operatorVersion: 4.14.0-160.hci
    platformVersion: 4.14.0-rc.7
  lastHeartbeat: "2023-11-03T05:41:24Z"
  state: Ready
```

**Comment by Madhu-1** [comment]
>F1103 05:39:24.438907       1 main.go:134] Failed to report status of storageClient 1cbb0e37-301b-427f-9b96-2161e4d48236: rpc error: code = InvalidArgument desc = Malformed ClientPlatformVersion: Version string empty

@leelavg As we have multiple problems, Are we going to have a different PR for the above problem?

**Comment by leelavg** [comment]
> > F1103 05:39:24.438907       1 main.go:134] Failed to report status of storageClient 1cbb0e37-301b-427f-9b96-2161e4d48236: rpc error: code = InvalidArgument desc = Malformed ClientPlatformVersion: Version string empty
> 
> @leelavg As we have multiple problems, Are we going to have a different PR for the above problem?
- this particular problem is kinda expected and it'll be fixed as part of BZ 2247743

**Comment by leelavg** [comment]
@Madhu-1 if above testing isn't enough for the vote, I tested deploying via OLM
```
# date; ko logs ocs-provider-server-766fcb944d-d2t5g | grep 'consumer.go:226'
Monday 06 November 2023 09:57:18 AM IST
I1106 04:25:01.129650       1 consumer.go:226] successfully updated Status for StorageConsumer storageconsumer-b67a611e-3c50-4eb6-aa74-5c789aaf7b3c
I1106 04:26:01.071069       1 consumer.go:226] successfully updated Status for StorageConsumer storageconsumer-b67a611e-3c50-4eb6-aa74-5c789aaf7b3c
I1106 04:27:01.271745       1 consumer.go:226] successfully updated Status for StorageConsumer storageconsumer-b67a611e-3c50-4eb6-aa74-5c789aaf7b3c
```

**Review by Madhu-1 — APPROVED** [review]

**Pull request merged**
