### PR TITLE
DFBUGS-32: Dummy

### PR DESCRIPTION
**Pull request by rewantsoni**
dummy PR to test backport change

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
@hoxhaeris @bradmwilliams can you please check why the bot is not adding the labels for the PR in this repo?
We have the necessary labels in the repo though: https://github.com/red-hat-storage/ocs-client-operator/labels?q=jira

**Comment by hoxhaeris** [comment]
> @hoxhaeris @bradmwilliams can you please check why the jira bot is not adding the labels for the PR in this repo? We have the necessary labels in the repo though: https://github.com/red-hat-storage/ocs-client-operator/labels?q=jira

Hi @Nikhil-Ladha, we'll have a look.

**Comment by hoxhaeris** [comment]
@Nikhil-Ladha , I've found the issue. The Jira plugin does not have access to this repository, hence the API call is failing with a 403. I'll check what needs to be done to fix this.

**Comment by hoxhaeris** [comment]
@Nikhil-Ladha, the bot (`openshift-ci-bot`) needs admin access to this repository for the labels to work properly. You'll need to grant this access yourself if you have the required permissions, or request it from the org/repo owners.

**Comment by Nikhil-Ladha** [comment]
From what I see, it is a part of the org: https://github.com/orgs/red-hat-storage/people?query=opens
And, that should work otherwise we would be seeing in other repos as well 🤔

**Comment by Nikhil-Ladha** [comment]
Seems like we need to re-authenticate the bot for newly created repos.
I see the same issue for `ceph-csi-operator` repo as well: https://github.com/red-hat-storage/ceph-csi-operator/pull/61

**Comment by Nikhil-Ladha** [comment]
The issue seems to be resolved now.
Thanks a lot @hoxhaeris for helping in sorting this issue out 🚀

**Pull request closed without merging**
